// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maolhkncqdqbfyaqepzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hb2xoa25jcWRxYmZ5YXFlcHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjI0ODYsImV4cCI6MjA3MzMzODQ4Nn0.bcZjVn4OVB3JtFDHaR8IHIQORa6Pqn9dHOEGuDdr-Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});